server:
  port: 8084
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialSize: 1
    maxActive: 5
    username: root
    password: 123456
    url: jdbc:mysql://[host]:[port]/[database]?serverTimezone=GMT%2B8&autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=true&allowMultiQueries=true&useAffectRows=true
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    mapUnderscoreToCamelCase: true
